#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Disable .bash_history
HISTFILE=/dev/null
HISTFILESIZE=0
HISTSIZE=0
export HISTFILE HISTFILESIZE HISTSIZE

# Disable .lesshst
LESSHISTFILE=/dev/null
LESSHISTSIZE=0
export LESSHISTFILE LESSHISTSIZE

# Harden EDITOR
EDITOR=rnano
export EDITOR

# Harden LESS
PAGER=less
SYSTEMD_PAGER=less
SYSTEMD_PAGERSECURE=1
LESSSECURE=1
export PAGER SYSTEMD_PAGER SYSTEMD_PAGERSECURE LESSSECURE

# Harden PATH
PATH="/usr/sbin:/usr/bin"
export PATH

# Unset various variables
unset LESSOPEN LESSCLOSE LOGNAME

# Enhance terminal
PROMPT_COMMAND='echo -en "\033]0; ${USER} @ ${PWD##*/} \a"'
PS1='\n\e[0;36m\w\e[m\n>'
COLORTERM=truecolor
TERM=xterm-256color
SYSTEMD_COLORS=1
export COLORTERM TERM SYSTEMD_COLORS

# Add apt alias's
alias aptu='sudo apt update && sudo apt full-upgrade -y'
alias aptuk='sudo ubuntu-mainline-kernel.sh -i --yes'
alias aptc='sudo apt autoremove -y && sudo apt autoclean && sudo apt clean'

# Add grep alias's
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias cgrep='cgrep --color=auto -C 1'

# Add ls alias's
alias ls='ls --color=auto'
alias ll='ls -la'

# Add session alias's and function's
alias sleave="sudo find /var/log -type f -exec rm -f {} \; && sudo journalctl --rotate --vacuum-time=1s && sudo bleachbit --preset --clean && bleachbit --preset --clean && systemctl poweroff"

supleave() {
	aptu
	aptuk	
	aptc
	
	local currentkernel="v$(uname -r | sed "s/-generic//g")"
	local kernelarray=($(ubuntu-mainline-kernel.sh -l))
	
  	for kernel in "${kernelarray[@]}"
  	do		
  	  	if [[ "${currentkernel}" != "${kernel}" ]]; then
    		sudo ubuntu-mainline-kernel.sh -u "${kernel}" --yes
		fi
  	done

	sudo update-grub
	
	sleave
}

# Add system alias's
alias serr="journalctl -b -p err"
alias swarn="journalctl -b -p warning"
